In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [4]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Input, Dense, GRU, Activation
from tensorflow.python.keras.optimizers import adam
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau

In [5]:
Mucuri = pd.read_csv('./train150_mucuri.txt', sep='\t', header = None)

In [6]:
Mucuri.head(10)

0   1     2   3          4          5          6          7            8
0  30  11  2015  14  13.012139  75.105481  27.516129  72.930636  1020.422601
1  30  11  2015  15  12.726087  68.334332  27.238095  75.212121  1020.394348
2  30  11  2015  16  12.081111  64.457865  27.105263  75.741379  1020.508333
3  30  11  2015  17  11.647222  53.842100  26.305556  75.302632  1020.611000
4  30  11  2015  18  11.064444  53.945279  25.464286  76.592593  1020.866500
5  30  11  2015  19  10.324444  51.320714  24.764706  83.344444  1021.286500
6  30  11  2015  20   9.862778  47.354507  24.310811  88.044643  1021.627500
7  30  11  2015  21   9.598889  41.816108  24.304348  91.329670  1021.892333
8  30  11  2015  22   9.488889  39.561270  24.500000  92.415385  1021.856167
9  30  11  2015  23   7.502222  37.881537  24.419355  93.629630  1021.834667

In [7]:
Mucuri.describe()

0           1       2           3           4           5  \
count  550.000000  550.000000   550.0  550.000000  550.000000  550.000000   
mean    12.087273   11.981818  2015.0   11.496364    8.176719   73.027647   
std      6.891273    0.133730     0.0    6.940745    2.724988   64.996263   
min      1.000000   11.000000  2015.0    0.000000    1.211905    1.448179   
25%      6.000000   12.000000  2015.0    5.250000    6.215278   38.605367   
50%     12.000000   12.000000  2015.0   11.000000    8.320000   59.019307   
75%     18.000000   12.000000  2015.0   17.750000   10.146806   83.329498   
max     30.000000   12.000000  2015.0   23.000000   13.572222  356.553715   

                6           7            8  
count  549.000000  550.000000   550.000000  
mean    24.443445   85.263578  1017.313986  
std      1.669638    8.579562     8.796185  
min     20.616279   46.355556   937.534333  
25%     23.314815   80.942222  1016.544542  
50%     24.336134   86.765805  1020.046750  
75%     25.359375   91.434531  1021.497917  
max     30.140625   98.000000  1023.726500

In [8]:
Mucuri.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    1
7    0
8    0
dtype: int64

In [9]:
Mucuri.update(Mucuri[6].fillna(Mucuri[6].mean()))

In [10]:
Mucuri.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [11]:
x_array = Mucuri.values 
x_array

array([[  30.        ,   11.        , 2015.        , ...,   27.51612903,
          72.93063584, 1020.422601  ],
       [  30.        ,   11.        , 2015.        , ...,   27.23809524,
          75.21212121, 1020.394348  ],
       [  30.        ,   11.        , 2015.        , ...,   27.10526316,
          75.74137931, 1020.508333  ],
       ...,
       [  23.        ,   12.        , 2015.        , ...,   22.60240964,
          79.80120482, 1016.323667  ],
       [  23.        ,   12.        , 2015.        , ...,   22.20325203,
          80.90740741, 1016.0715    ],
       [  23.        ,   12.        , 2015.        , ...,   22.02409639,
          84.76111111, 1014.882833  ]])

In [12]:
y_array = list(Mucuri[4].values)
y_array

[13.01213875,
 12.72608696,
 12.08111113,
 11.64722224,
 11.06444444,
 10.32444445,
 9.862777788999999,
 9.598888869,
 9.488888884,
 7.502222217000001,
 7.081111103,
 8.003333415,
 8.149444466,
 8.962777792,
 7.672777804,
 6.331666684,
 4.587179497,
 4.961111107,
 5.65944445,
 5.417777794,
 7.3039106039999995,
 8.602777796,
 11.70611108,
 12.30500005,
 12.08722222,
 11.34166668,
 10.69388894,
 9.519444438999999,
 8.94000002,
 8.105000016,
 7.637777778999999,
 6.661111122,
 4.801111111,
 3.717777774,
 2.141666657,
 2.77055556,
 2.7494444380000003,
 3.912222219,
 5.532222231,
 6.351666662,
 4.5777777760000005,
 3.918888871,
 4.281111113,
 3.5999999910000002,
 3.9055555539999998,
 7.156111113,
 8.167222222000001,
 8.547777798,
 9.712222205,
 10.48055558,
 10.28333334,
 9.587777767999999,
 9.037777797,
 7.906666687,
 7.552222284,
 6.913333315,
 6.856666679,
 6.588333339,
 6.380555564,
 6.203888903999999,
 6.588888878,
 7.843888892000001,
 8.235555543,
 8.783333349,
 6.128333334,
 3.1905555

In [13]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(9, activation='relu', input_shape=(9,)),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear'),
  ])

  model.compile(optimizer='adam',
                loss='mse',
                metrics=['mae'])
  return model

In [14]:
model = get_compiled_model()
model.fit(x_array, y_array, epochs=6)

W0826 15:39:29.094530 10436 deprecation.py:506] From D:\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Epoch 1/6
550/550 [==============================] - 0s 160us/sample - loss: 228436.3440 - mean_absolute_error: 476.8796
Epoch 2/6
550/550 [==============================] - 0s 44us/sample - loss: 141834.7328 - mean_absolute_error: 375.6530
Epoch 3/6
550/550 [==============================] - 0s 34us/sample - loss: 81600.6326 - mean_absolute_error: 284.0302
Epoch 4/6
550/550 [==============================] - 0s 38us/sample - loss: 23942.3778 - mean_absolute_error: 149.5540
Epoch 5/6
550/550 [==============================] - 0s 38us/sample - loss: 2121.2268 - mean_absolute_error: 39.7445
Epoch 6/6
550/550 [==============================] - 0s 40us/sample - loss: 135.8159 - mean_absolute_error: 9.3972


In [15]:
model.evaluate(x_array, y_array)

550/550 [==============================] - 0s 47us/sample - loss: 200.1863 - mean_absolute_error: 11.9336


[200.18631763805044, 11.9336195]

In [16]:
z_array = model.predict(x_array) 
z_array

array([[  6.5735044 ],
       [  8.440616  ],
       [  8.921802  ],
       [  9.049502  ],
       [  9.512286  ],
       [ 13.926654  ],
       [ 17.104174  ],
       [ 19.559572  ],
       [ 20.386538  ],
       [ 21.33246   ],
       [ 30.889635  ],
       [ 30.672136  ],
       [ 30.95894   ],
       [ 30.805437  ],
       [ 31.484118  ],
       [ 30.766954  ],
       [ 29.536852  ],
       [ 25.729342  ],
       [ 19.694597  ],
       [ 14.733859  ],
       [ 22.009798  ],
       [ 20.494493  ],
       [ 18.37816   ],
       [ 16.845354  ],
       [ 19.175127  ],
       [ 19.110903  ],
       [ 20.932955  ],
       [ 22.11722   ],
       [ 22.178438  ],
       [ 21.864351  ],
       [ 21.411547  ],
       [ 21.72809   ],
       [ 22.471254  ],
       [ 22.962587  ],
       [ 28.992739  ],
       [ 30.905428  ],
       [  5.7588224 ],
       [  6.7285795 ],
       [  6.9611387 ],
       [  5.4232664 ],
       [  6.0065794 ],
       [  3.8236265 ],
       [ 22.395632  ],
       [ 16

In [17]:
a = pd.DataFrame(x_array)
a[4] = z_array
x_array = a.values
x_array

array([[  30.        ,   11.        , 2015.        , ...,   27.51612903,
          72.93063584, 1020.422601  ],
       [  30.        ,   11.        , 2015.        , ...,   27.23809524,
          75.21212121, 1020.394348  ],
       [  30.        ,   11.        , 2015.        , ...,   27.10526316,
          75.74137931, 1020.508333  ],
       ...,
       [  23.        ,   12.        , 2015.        , ...,   22.60240964,
          79.80120482, 1016.323667  ],
       [  23.        ,   12.        , 2015.        , ...,   22.20325203,
          80.90740741, 1016.0715    ],
       [  23.        ,   12.        , 2015.        , ...,   22.02409639,
          84.76111111, 1014.882833  ]])

In [18]:
w_array = model.predict(x_array) 
w_array

array([[ 7.10396099e+00],
       [ 8.79373455e+00],
       [ 9.18211651e+00],
       [ 9.26355267e+00],
       [ 9.64020061e+00],
       [ 1.36298246e+01],
       [ 1.65075397e+01],
       [ 1.87388630e+01],
       [ 1.94886646e+01],
       [ 2.01929340e+01],
       [ 2.89279652e+01],
       [ 2.88043690e+01],
       [ 2.90795460e+01],
       [ 2.90057545e+01],
       [ 2.95222034e+01],
       [ 2.87536335e+01],
       [ 2.74812031e+01],
       [ 2.40182056e+01],
       [ 1.85381489e+01],
       [ 1.39662657e+01],
       [ 2.07981434e+01],
       [ 1.95147114e+01],
       [ 1.78284779e+01],
       [ 1.64712391e+01],
       [ 1.85911121e+01],
       [ 1.84707966e+01],
       [ 2.00893269e+01],
       [ 2.10792561e+01],
       [ 2.10877094e+01],
       [ 2.07306843e+01],
       [ 2.02767048e+01],
       [ 2.04866962e+01],
       [ 2.10153217e+01],
       [ 2.13769093e+01],
       [ 2.67804127e+01],
       [ 2.85872974e+01],
       [ 5.51088238e+00],
       [ 6.49649334e+00],
       [ 6.8

In [19]:
line = x_array[0,:]
for i in range(12):
    vel = model.predict(np.reshape(line, (1,9)))
    line = x_array[i+1,:]
    line[4] = vel 
    print(vel)
    

[[7.1039457]]
[[8.903811]]
[[9.183551]]
[[9.25246]]
[[9.661563]]
[[13.981204]]
[[16.764772]]
[[18.969149]]
[[19.605425]]
[[20.335161]]
[[29.797579]]
[[28.876421]]
